[project]
name = "youtokentome"
version = "1.0.6"
dependencies = ["Click>=7.0"]

[build-system]
# Minimum requirements for the build system to execute.
requires = ["cython<3", "setuptools"]
build-backend = "setuptools.build_meta"
